site_name: head(amame) Documentation
site_url: https://docs.headamame.com
site_description: Open-source DIY headphone kits - Build your own high-end audio
site_author: head(amame) Team

repo_url: https://github.com/headamame/docs
repo_name: headamame/docs

copyright: Copyright &copy; 2024 head(amame) - Open Source Audio

theme:
  name: material
  # logo: assets/images/logo.png
  # favicon: assets/images/favicon.png
  
  palette:
    # Light/dark mode toggle
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Inter
    code: JetBrains Mono
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
# Disabled social cards plugin until real logo is added
  # - social:
  #     cards_layout_options:
  #       background_color: "#4c1d95"
  #       color: "#ffffff"
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: headamame
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/headamame
      name: Discord Community
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/headamame
      name: Reddit Community
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/headamame
      name: Instagram
    - icon: fontawesome/brands/github
      link: https://github.com/headamame
      name: GitHub Repository
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@headamame
      name: YouTube Channel
  version:
    provider: mike
    default: stable
  status:
    new: Recently added
    deprecated: Deprecated
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    Build Guide: build
    Technical: tech
    DIY: diy
    Audio: audio

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - head(amame):
    - Overview: head-amame/index.md
    - Getting Started: head-amame/getting-started/index.md
    - 3D Printing Guide: head-amame/build-guide/3d-printing.md
    - Bill of Materials: head-amame/technical/bom.md
  - min(amame):
    - Overview: min-amame/index.md
    - Quick Start: min-amame/getting-started/quick-start.md
  - Community: community/index.md
  - Support: support/faq.md
  - Blog: blog/index.md